language: php

php:
  - 5.5
  - 5.6
  - 7.1

before_script:
  - composer self-update
  - composer update --prefer-source; composer install --dev --prefer-source;

script:
  - ./vendor/bin/phpunit -c ./test/phpunit.xml --coverage-clover ./build/logs/clover.xml